name: Expo Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Step 5: Authenticate with Expo using EXPO_TOKEN
      - name: Authenticate with Expo using token
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_SKIP_AUTO_FINGERPRINT: 1
        run: echo "Authenticated with Expo"

      # Step 6: Build the app using EAS
      - name: Build with EAS
        run: eas build --platform android --non-interactive
